export const transpileToC = (projectStructure, standardHeaders = []) => {
    let stdFunctions = {};
    let customIncludes = ``;

    standardHeaders.forEach(([filename, content]) => {
        customIncludes += `#include "${filename}"\n`;
        const regex = /void\s+([A-Za-z0-9_]+)_Call\s*\(([^)]+)\)/g;
        let match;
        while ((match = regex.exec(content)) !== null) {
            const blockType = match[1];
            const params = match[2];
            stdFunctions[blockType] = { hasTime: params.includes('TIME') };
        }
    });

    let header = `// Autogenerated by KronEditor CTranspiler
#ifndef PLC_H
#define PLC_H

#include <stdint.h>
#include <stdbool.h>
#include <string.h>
${customIncludes}
`;

    let source = `// Autogenerated by KronEditor CTranspiler\n#include "plc.h"\n\n#if defined(__linux__) || defined(__APPLE__) || defined(_WIN32)\n#include <stdio.h>\n#include <time.h>\n#include <unistd.h>\n#endif\n\n`;

    // 1. Data Types (Header only)
    if (projectStructure.dataTypes && projectStructure.dataTypes.length > 0) {
        header += `// --- DATA TYPES ---\n`;
        projectStructure.dataTypes.forEach(dt => {
            header += transpileDataType(dt);
        });
    }

    // 2. Global Variables
    const config = projectStructure.resources?.find(r => r.id === 'res_config');
    if (config && config.content.globalVars && config.content.globalVars.length > 0) {
        header += `// --- GLOBAL VARIABLES ---\n`;
        config.content.globalVars.forEach(v => {
            let initVal = v.initialValue ? ` = ${v.initialValue}` : '';
            if (v.type === 'STRING' && v.initialValue) initVal = ` = "${v.initialValue}"`;
            header += `${mapType(v.type)} ${v.name}${initVal};\n`;
        });
        header += `\n`;
    }

    // 3. Function Blocks (State Structures)
    if (projectStructure.functionBlocks && projectStructure.functionBlocks.length > 0) {
        header += `// --- FUNCTION BLOCK STATES ---\n`;
        projectStructure.functionBlocks.forEach(fb => {
            header += `typedef struct {\n`;
            fb.content.variables.forEach(v => {
                header += `    ${mapType(v.type)} ${v.name};\n`;
            });
            header += `} ${fb.name};\n\n`;
        });
    }

    // 4. Function and Program Signatures
    header += `// --- SIGNATURES ---\n`;

    if (projectStructure.functions) {
        projectStructure.functions.forEach(fn => {
            const retType = mapType(fn.returnType || 'VOID');
            let fnName = (fn.name || '').trim().replace(/\s+/g, '_');
            header += `static inline ${retType} ${fnName}();\n`;
        });
    }

    if (projectStructure.functionBlocks) {
        projectStructure.functionBlocks.forEach(fb => {
            let fbName = (fb.name || '').trim().replace(/\s+/g, '_');
            header += `static inline void ${fbName}_Execute(${fbName} *instance);\n`;
        });
    }

    if (projectStructure.programs) {
        projectStructure.programs.forEach(prog => {
            let progName = (prog.name || '').trim().replace(/\s+/g, '_');
            header += `static inline void ${progName}();\n`;
        });
    }

    header += `\n// --- IMPLEMENTATIONS ---\n`;

    if (projectStructure.functions) {
        header += `// --- FUNCTIONS ---\n`;
        projectStructure.functions.forEach(fn => {
            header += transpilePOUSource(fn, 'function', stdFunctions, fn.name);
        });
    }

    if (projectStructure.functionBlocks) {
        header += `// --- FUNCTION BLOCKS ---\n`;
        projectStructure.functionBlocks.forEach(fb => {
            header += transpilePOUSource(fb, 'function_block', stdFunctions, fb.name);
        });
    }

    if (projectStructure.programs) {
        header += `// --- PROGRAMS ---\n`;
        projectStructure.programs.forEach(prog => {
            let progName = (prog.name || '').trim().replace(/\s+/g, '_');
            // Allocate static program instances of FBs if they exist
            prog.content.variables.forEach(v => {
                let vName = (v.name || '').trim().replace(/\s+/g, '_');
                if (isFBType(v.type, projectStructure) || stdFunctions[v.type]) {
                    header += `${v.type} prog_${progName}_inst_${vName};\n`;
                } else {
                    // Global internal variables for simple programs
                    header += `${mapType(v.type)} prog_${progName}_${vName};\n`;
                }
            });
            header += transpilePOUSource(prog, 'program', stdFunctions, progName);
        });
    }

    header += `\n#endif // PLC_H\n`;

    // --- 5. DETERMINISTIC SCAN LOOP ---
    source += generateMainLoop(projectStructure, config);

    return { header, source };
};

const isFBType = (type, structure) => {
    return structure.functionBlocks?.some(fb => fb.name === type);
};

const mapIECtoTimeMs = (iecTimeStr) => {
    if (!iecTimeStr) return 10;
    const str = iecTimeStr.toUpperCase().replace('T#', '');
    if (str.endsWith('MS')) return parseInt(str.replace('MS', ''));
    if (str.endsWith('S')) return parseInt(str.replace('S', '')) * 1000;
    return 10; // Default 10ms
};

const generateMainLoop = (projectStructure, config) => {
    let mainSrc = `\n// --- DETERMINISTIC SCAN LOOP ---\n`;

    // Provide a Cortex-M4 compatible fallback main loop
    mainSrc += `#if defined(__linux__) || defined(__APPLE__) || defined(_WIN32)\n`;
    mainSrc += `int main() {\n`;
    mainSrc += `    printf("PLC Execution Engine Started...\\n");\n\n`;

    // 1. Tick trackers
    mainSrc += `    struct timespec req, rem;\n`;
    mainSrc += `    req.tv_sec = 0;\n`;
    mainSrc += `    req.tv_nsec = 1000000; // 1ms base tick\n\n`;
    mainSrc += `    uint64_t ms_tick = 0;\n\n`;

    // 2. Discover Task mappings and Instances
    let programTasks = [];

    if (config && config.content.instances) {
        config.content.instances.forEach(inst => {
            const task = config.content.tasks?.find(t => t.name === inst.task);
            let pName = (inst.program || '').trim().replace(/\s+/g, '_');
            if (task) {
                programTasks.push({
                    name: pName,
                    intervalMs: mapIECtoTimeMs(task.interval)
                });
            } else {
                programTasks.push({ name: pName, intervalMs: 10 }); // Default
            }
        });
    } else if (projectStructure.programs) {
        projectStructure.programs.forEach(p => {
            let pName = (p.name || '').trim().replace(/\s+/g, '_');
            programTasks.push({ name: pName, intervalMs: 10 });
        });
    }

    mainSrc += `    while(1) {\n`;

    // 3. Scan logic
    programTasks.forEach(pt => {
        mainSrc += `        if (ms_tick % ${pt.intervalMs} == 0) {\n`;
        mainSrc += `            ${pt.name}();\n`;
        mainSrc += `        }\n`;
    });

    // 4. Advance time
    mainSrc += `        nanosleep(&req, &rem);\n`;
    mainSrc += `        ms_tick++;\n`;
    mainSrc += `    }\n`;
    mainSrc += `    return 0;\n}\n`;

    mainSrc += `#else\n\n`;
    mainSrc += `// Bare-metal / Cortex-M4 execution engine\n`;
    mainSrc += `// You must provide a SysTick handler or external timer to increment ms_tick\n`;
    mainSrc += `extern volatile uint64_t ms_tick;\n\n`;
    mainSrc += `void PLC_Run() {\n`;
    programTasks.forEach(pt => {
        mainSrc += `    if (ms_tick % ${pt.intervalMs} == 0) {\n`;
        mainSrc += `        ${pt.name}();\n`;
        mainSrc += `    }\n`;
    });
    mainSrc += `}\n\n`;
    mainSrc += `#endif\n`;

    return mainSrc;
};

const transpilePOUSource = (pou, category, stdFunctions = {}, parentName = '') => {
    let src = ``;
    let safeName = (pou.name || '').trim().replace(/\s+/g, '_');
    let sig = `static inline void ${safeName}()`;

    if (category === 'function') {
        const retType = mapType(pou.returnType || 'VOID');
        sig = `static inline ${retType} ${safeName}()`;
    } else if (category === 'function_block') {
        sig = `static inline void ${safeName}_Execute(${safeName} *instance)`;
    }

    src += `${sig} {\n`;

    if (pou.type === 'ST') {
        src += transpileSTLogics(pou.content.code, stdFunctions, safeName, category);
    } else if (pou.type === 'LD') {
        src += transpileLDLogics(pou.content.rungs, stdFunctions, safeName, category);
    }

    src += `}\n\n`;
    return src;
};

const transpileSTLogics = (code, stdFunctions = {}, parentName = '', category = 'program') => {
    if (!code) return `    // ST Implementation Empty\n`;
    // Basic structural ST -> C mapping bypass
    let lines = code.split('\\n');
    let out = '';
    lines.forEach(l => {
        let cl = l.trim()
            .replace(/:=/g, '=')
            .replace(/AND/g, '&&')
            .replace(/OR/g, '||')
            .replace(/NOT/g, '!');
        if (cl) out += `    ${cl}\n`;
    });
    return out || `    // ST parsing placeholder\n`;
};

const transpileLDLogics = (rungs, stdFunctions = {}, parentName = '', category = 'program') => {
    if (!rungs || rungs.length === 0) return `    // LD Implementation Empty\n`;

    let out = '';
    rungs.forEach((rung, i) => {
        out += `    // Rung ${i}\n`;

        let pathConds = [];
        let assignments = [];
        let currentCondStr = 'true';

        if (!rung.blocks || rung.blocks.length === 0) {
            out += `    // Empty Rung\n`;
            return;
        }

        rung.blocks.forEach(b => {
            const type = b.type || '';
            const data = b.data || {};
            const subType = data.subType || '';

            if (type === 'Contact') {
                const varName = data.values?.var || data.instanceName;
                if (varName) {
                    let vSafe = varName.trim().replace(/\s+/g, '_');
                    if (subType === 'NC' || subType === 'Falling') {
                        pathConds.push(`!${vSafe}`);
                    } else {
                        pathConds.push(`${vSafe}`);
                    }
                }
            } else if (type === 'Coil') {
                const varName = data.values?.coil || data.instanceName;
                if (varName) {
                    let vSafe = varName.trim().replace(/\s+/g, '_');
                    currentCondStr = pathConds.length > 0 ? pathConds.join(' && ') : 'true';

                    if (category === 'program') {
                        vSafe = `prog_${parentName}_${vSafe}`; // Apply global prefix for program simple variables
                        // Note: If vSafe targets a global resource var, it wouldn't have this prefix, but this covers local logic
                    }

                    if (subType === 'Negated') {
                        assignments.push(`    ${vSafe} = !(${currentCondStr});\n`);
                    } else if (subType === 'Set') {
                        assignments.push(`    if (${currentCondStr}) { ${vSafe} = true; }\n`);
                    } else if (subType === 'Reset') {
                        assignments.push(`    if (${currentCondStr}) { ${vSafe} = false; }\n`);
                    } else {
                        assignments.push(`    ${vSafe} = (${currentCondStr});\n`);
                    }
                }
            } else {
                // Function Block Execution
                const instName = data.instanceName || type;
                let iSafe = instName.trim().replace(/\s+/g, '_');
                currentCondStr = pathConds.length > 0 ? pathConds.join(' && ') : 'true';

                let callTarget = iSafe;
                if (category === 'program') {
                    callTarget = `prog_${parentName}_inst_${iSafe}`;
                } else if (category === 'function_block') {
                    callTarget = `instance->${iSafe}`;
                }

                if (stdFunctions[type]) {
                    const timeArg = stdFunctions[type].hasTime ? ', ms_tick' : '';
                    assignments.push(`    if (${currentCondStr}) { ${type}_Call(&${callTarget}${timeArg}); }\n`);
                } else {
                    assignments.push(`    if (${currentCondStr}) { ${type}_Execute(&${callTarget}); }\n`);
                }
            }
        });

        if (assignments.length > 0) {
            assignments.forEach(a => {
                out += a;
            });
        }
    });

    return out;
};

const mapType = (iecType) => {
    const typeMap = {
        'BOOL': 'bool',
        'SINT': 'int8_t',
        'INT': 'int16_t',
        'DINT': 'int32_t',
        'LINT': 'int64_t',
        'USINT': 'uint8_t',
        'UINT': 'uint16_t',
        'UDINT': 'uint32_t',
        'ULINT': 'uint64_t',
        'REAL': 'float',
        'LREAL': 'double',
        'BYTE': 'uint8_t',
        'WORD': 'uint16_t',
        'DWORD': 'uint32_t',
        'LWORD': 'uint64_t',
        'TIME': 'uint32_t',
        'STRING': 'char*',
        'VOID': 'void'
    };
    return typeMap[iecType] || iecType; // Fallback to custom name
};

const transpileDataType = (dt) => {
    let code = '';
    if (dt.type === 'Enumerated') {
        code += `typedef enum {\n`;
        dt.content.values.forEach((val, i) => {
            code += `    ${val.identifier}${val.value ? ` = ${val.value}` : ''}${i < dt.content.values.length - 1 ? ',' : ''}\n`;
        });
        code += `} ${dt.name};\n\n`;
    } else if (dt.type === 'Structure') {
        code += `typedef struct {\n`;
        dt.content.members.forEach(member => {
            code += `    ${mapType(member.type)} ${member.name};\n`;
        });
        code += `} ${dt.name};\n\n`;
    } else if (dt.type === 'Array') {
        const totalSize = dt.content.dimensions.reduce((acc, dim) => acc * ((parseInt(dim.max) - parseInt(dim.min)) + 1), 1);
        code += `typedef struct {\n`;
        code += `    ${mapType(dt.content.baseType)} data[${totalSize}];\n`;
        code += `} ${dt.name};\n\n`;
    }
    return code;
};
