export const transpileToC = (projectStructure, standardHeaders = []) => {
    let stdFunctions = {};
    let customIncludes = ``;

    standardHeaders.forEach(([filename, content]) => {
        customIncludes += `#include "${filename}"\n`;
        const regex = /void\s+([A-Za-z0-9_]+)_Call\s*\(([^)]+)\)/g;
        let match;
        while ((match = regex.exec(content)) !== null) {
            const blockType = match[1];
            const params = match[2];
            stdFunctions[blockType] = { hasTime: params.includes('TIME') };
        }
    });

    let header = `// Autogenerated by KronEditor CTranspiler
#ifndef PLC_H
#define PLC_H

#include <stdint.h>
#include <stdbool.h>
#include <string.h>
${customIncludes}

extern volatile uint64_t us_tick;

`;

    let source = `// Autogenerated by KronEditor CTranspiler\n#include "plc.h"\n\n#if defined(__linux__) || defined(__APPLE__) || defined(_WIN32)\n#include <time.h>\n#include <unistd.h>\n#endif\n\n`;

    let variableTable = {
        dataTypes: {},
        globalVars: {},
        programs: {}
    };

    // 1. Data Types (Header only)
    if (projectStructure.dataTypes && projectStructure.dataTypes.length > 0) {
        header += `// --- DATA TYPES ---\n`;
        projectStructure.dataTypes.forEach(dt => {
            header += transpileDataType(dt);
            // Record structured mapping
            variableTable.dataTypes[dt.name] = {
                type: dt.type,
                content: dt.content
            };
        });
    }

    // 2. Global Variables
    const config = projectStructure.resources?.find(r => r.id === 'res_config');
    if (config && config.content.globalVars && config.content.globalVars.length > 0) {
        header += `// --- GLOBAL VARIABLES ---\n`;
        config.content.globalVars.forEach(v => {
            let initVal = v.initialValue ? ` = ${v.initialValue}` : '';
            if (v.type === 'STRING' && v.initialValue) initVal = ` = "${v.initialValue}"`;
            header += `${mapType(v.type)} ${v.name}${initVal};\n`;
            variableTable.globalVars[v.name] = {
                type: v.type,
                initialValue: v.initialValue || null
            };
        });
        header += `\n`;
    }

    // 3. Function Blocks (State Structures)
    if (projectStructure.functionBlocks && projectStructure.functionBlocks.length > 0) {
        header += `// --- FUNCTION BLOCK STATES ---\n`;
        projectStructure.functionBlocks.forEach(fb => {
            header += `typedef struct {\n`;
            fb.content.variables.forEach(v => {
                header += `    ${mapType(v.type)} ${v.name};\n`;
            });
            header += `} ${fb.name};\n\n`;
        });
    }

    // 4. Function and Program Signatures
    header += `// --- SIGNATURES ---\n`;

    if (projectStructure.functions) {
        projectStructure.functions.forEach(fn => {
            const retType = mapType(fn.returnType || 'VOID');
            let fnName = (fn.name || '').trim().replace(/\s+/g, '_');
            header += `static inline ${retType} ${fnName}();\n`;
        });
    }

    if (projectStructure.functionBlocks) {
        projectStructure.functionBlocks.forEach(fb => {
            let fbName = (fb.name || '').trim().replace(/\s+/g, '_');
            header += `static inline void ${fbName}_Execute(${fbName} *instance);\n`;
        });
    }

    if (projectStructure.programs) {
        projectStructure.programs.forEach(prog => {
            let progName = (prog.name || '').trim().replace(/\s+/g, '_');
            header += `static inline void ${progName}();\n`;
        });
    }

    header += `\n// --- IMPLEMENTATIONS ---\n`;

    if (projectStructure.functions) {
        header += `// --- FUNCTIONS ---\n`;
        projectStructure.functions.forEach(fn => {
            header += transpilePOUSource(fn, 'function', stdFunctions, fn.name);
        });
    }

    if (projectStructure.functionBlocks) {
        header += `// --- FUNCTION BLOCKS ---\n`;
        projectStructure.functionBlocks.forEach(fb => {
            header += transpilePOUSource(fb, 'function_block', stdFunctions, fb.name);
        });
    }

    if (projectStructure.programs) {
        header += `// --- PROGRAMS ---\n`;
        projectStructure.programs.forEach(prog => {
            let progName = (prog.name || '').trim().replace(/\s+/g, '_');

            variableTable.programs[progName] = { variables: {} };

            // Allocate static program instances of FBs if they exist
            prog.content.variables.forEach(v => {
                let vName = (v.name || '').trim().replace(/\s+/g, '_');
                if (isFBType(v.type, projectStructure) || stdFunctions[v.type]) {
                    header += `${v.type} prog_${progName}_inst_${vName};\n`;
                } else {
                    // Global internal variables for simple programs
                    header += `${mapType(v.type)} prog_${progName}_${vName};\n`;
                }

                variableTable.programs[progName].variables[vName] = {
                    type: v.type,
                    c_symbol: (isFBType(v.type, projectStructure) || stdFunctions[v.type]) ? `prog_${progName}_inst_${vName}` : `prog_${progName}_${vName}`,
                    initialValue: v.initialValue || null
                };
            });
            header += transpilePOUSource(prog, 'program', stdFunctions, progName);
        });
    }

    header += `\n#endif // PLC_H\n`;

    // --- 5. DETERMINISTIC SCAN LOOP ---
    source += generateMainLoop(projectStructure, config);

    return { header, source, variableTable };
};

const isFBType = (type, structure) => {
    return structure.functionBlocks?.some(fb => fb.name === type);
};

const mapIECtoTimeUs = (iecTimeStr) => {
    if (!iecTimeStr) return 10000;
    const str = iecTimeStr.toUpperCase().replace('T#', '').replace('TIME#', '');
    if (str.endsWith('MS')) return parseInt(str.replace('MS', '')) * 1000;
    if (str.endsWith('US')) return parseInt(str.replace('US', ''));
    if (str.endsWith('S')) return parseInt(str.replace('S', '')) * 1000000;
    return 10000; // Default 10000us (10ms)
};



const generateMainLoop = (projectStructure, config) => {
    let mainSrc = `\n// --- DETERMINISTIC SCAN LOOP ---\n`;

    mainSrc += `\n// Global Tick Variable\n`;
    mainSrc += `#if defined(__linux__) || defined(__APPLE__) || defined(_WIN32)\n`;
    mainSrc += `// Defined here for simulation\n`;
    mainSrc += `extern volatile uint64_t us_tick;\n`;
    mainSrc += `volatile uint64_t us_tick = 0;\n`;
    mainSrc += `#else\n`;
    mainSrc += `// For Cortex-M4 and bare-metal targets, us_tick MUST be defined\n`;
    mainSrc += `// and incremented in your hardware timer interrupt.\n`;
    mainSrc += `// Example: volatile uint64_t us_tick = 0; void Timer_Handler(void) { us_tick += 10; }\n`;
    mainSrc += `#endif\n\n`;
    // Provide a Cortex-M4 compatible fallback main loop
    mainSrc += `#if defined(__linux__) || defined(__APPLE__) || defined(_WIN32)\n`;
    mainSrc += `int main() {\n`;

    // 1. Tick trackers
    mainSrc += `    struct timespec req, rem;\n`;
    mainSrc += `    req.tv_sec = 0;\n`;
    mainSrc += `    req.tv_nsec = 1000000; // 1ms base tick\n\n`;

    // 2. Discover Task mappings and Instances
    let programTasks = [];

    if (config && config.content.instances) {
        config.content.instances.forEach(inst => {
            const task = config.content.tasks?.find(t => t.name === inst.task);
            let pName = (inst.program || '').trim().replace(/\s+/g, '_');
            if (task) {
                programTasks.push({
                    name: pName,
                    intervalUs: mapIECtoTimeUs(task.interval)
                });
            } else {
                programTasks.push({ name: pName, intervalUs: 10000 }); // Default 10ms
            }
        });
    } else if (projectStructure.programs) {
        projectStructure.programs.forEach(p => {
            let pName = (p.name || '').trim().replace(/\s+/g, '_');
            programTasks.push({ name: pName, intervalUs: 10000 });
        });
    }

    mainSrc += `    while(1) {\n`;

    // 3. Scan logic
    programTasks.forEach(pt => {
        mainSrc += `        if (us_tick % ${pt.intervalUs} == 0) {\n`;
        mainSrc += `            ${pt.name}();\n`;
        mainSrc += `        }\n`;
    });

    // 4. Advance time
    mainSrc += `        nanosleep(&req, &rem);\n`;
    mainSrc += `        us_tick += 1000;\n`; // Advance 1000us (1ms)
    mainSrc += `    }\n`;
    mainSrc += `    return 0;\n}\n`;

    mainSrc += `#else\n\n`;
    mainSrc += `// Bare-metal / Cortex-M4 execution engine\n`;
    mainSrc += `// You must provide a timer to increment us_tick\n`;
    mainSrc += `void PLC_Run() {\n`;
    programTasks.forEach(pt => {
        mainSrc += `    if (us_tick % ${pt.intervalUs} == 0) {\n`;
        mainSrc += `        ${pt.name}();\n`;
        mainSrc += `    }\n`;
    });
    mainSrc += `}\n\n`;
    mainSrc += `#endif\n`;

    return mainSrc;
};

const transpilePOUSource = (pou, category, stdFunctions = {}, parentName = '') => {
    let src = ``;
    let safeName = (pou.name || '').trim().replace(/\s+/g, '_');
    let sig = `static inline void ${safeName}()`;

    if (category === 'function') {
        const retType = mapType(pou.returnType || 'VOID');
        sig = `static inline ${retType} ${safeName}()`;
    } else if (category === 'function_block') {
        sig = `static inline void ${safeName}_Execute(${safeName} *instance)`;
    }

    src += `${sig} {\n`;

    if (pou.type === 'ST') {
        src += transpileSTLogics(pou.content.code, stdFunctions, safeName, category);
    } else if (pou.type === 'LD') {
        src += transpileLDLogics(pou.content.rungs, stdFunctions, safeName, category);
    }

    src += `}\n\n`;
    return src;
};

const transpileSTLogics = (code, stdFunctions = {}, parentName = '', category = 'program') => {
    if (!code) return `    // ST Implementation Empty\n`;
    // Basic structural ST -> C mapping bypass
    let lines = code.split('\\n');
    let out = '';
    lines.forEach(l => {
        let cl = l.trim()
            .replace(/:=/g, '=')
            .replace(/AND/g, '&&')
            .replace(/OR/g, '||')
            .replace(/NOT/g, '!');
        if (cl) out += `    ${cl}\n`;
    });
    return out || `    // ST parsing placeholder\n`;
};

const transpileLDLogics = (rungs, stdFunctions = {}, parentName = '', category = 'program') => {
    if (!rungs || rungs.length === 0) return `    // LD Implementation Empty\n`;

    let out = '';
    rungs.forEach((rung, i) => {
        out += `    // Rung ${i}\n`;

        if (!rung.blocks || rung.blocks.length === 0) {
            out += `    // Empty Rung\n`;
            return;
        }

        // 1. Build graph for topological sort
        let adjacency = {};
        let incomming = {};
        let nodeMap = {};

        rung.blocks.forEach(b => {
            nodeMap[b.id] = b;
            adjacency[b.id] = [];
            incomming[b.id] = 0;
        });

        (rung.connections || []).forEach(c => {
            if (adjacency[c.source] && incomming[c.target] !== undefined) {
                adjacency[c.source].push(c.target);
                incomming[c.target]++;
            }
        });

        // 2. Topological sort
        let queue = [];
        let sorted = [];
        Object.keys(incomming).forEach(id => {
            if (incomming[id] === 0) queue.push(id);
        });

        while (queue.length > 0) {
            let curr = queue.shift();
            sorted.push(curr);
            adjacency[curr].forEach(child => {
                incomming[child]--;
                if (incomming[child] === 0) queue.push(child);
            });
        }

        // Append any remaining blocks 
        rung.blocks.forEach(b => {
            if (!sorted.includes(b.id)) {
                sorted.push(b.id);
            }
        });

        // 3. Generate C code in topological order
        sorted.forEach((blockId, idx) => {
            const b = nodeMap[blockId];
            const type = b.type || '';
            const data = b.data || {};
            const subType = data.subType || '';

            const bOut = `out_b${idx}`;

            // Calculate input condition
            let inConds = [];
            (rung.connections || []).forEach(c => {
                if (c.target === blockId) {
                    if (c.source && c.source.startsWith('terminal_left')) {
                        inConds.push('true');
                    } else {
                        const sIdx = sorted.indexOf(c.source);
                        inConds.push(`out_b${sIdx >= 0 ? sIdx : 0}`);
                    }
                }
            });
            let inExpr = inConds.length > 0 ? `(${inConds.join(' || ')})` : 'true';

            out += `    bool ${bOut} = false;\n`;

            if (type === 'Contact') {
                const varName = data.values?.var || data.instanceName;
                if (varName) {
                    let vSafe = varName.trim().replace(/\s+/g, '_');

                    if (category === 'program') {
                        vSafe = `prog_${parentName}_${vSafe}`; // Apply global prefix for program simple variables
                    } else if (category === 'function_block') {
                        vSafe = `instance->${vSafe}`; // Apply FB instance prefix
                    }

                    if (subType === 'NC' || subType === 'Falling') {
                        out += `    ${bOut} = ${inExpr} && !${vSafe};\n`;
                    } else {
                        out += `    ${bOut} = ${inExpr} && ${vSafe};\n`;
                    }
                }
            } else if (type === 'Coil') {
                const varName = data.values?.coil || data.instanceName;
                if (varName) {
                    let vSafe = varName.trim().replace(/\s+/g, '_');

                    if (category === 'program') {
                        vSafe = `prog_${parentName}_${vSafe}`; // Apply global prefix for program simple variables
                    } else if (category === 'function_block') {
                        vSafe = `instance->${vSafe}`; // Apply FB instance prefix
                    }

                    // Coil output is whatever went into it
                    out += `    ${bOut} = ${inExpr};\n`;

                    if (subType === 'Negated') {
                        out += `    ${vSafe} = !(${bOut});\n`;
                    } else if (subType === 'Set') {
                        out += `    if (${bOut}) { ${vSafe} = true; }\n`;
                    } else if (subType === 'Reset') {
                        out += `    if (${bOut}) { ${vSafe} = false; }\n`;
                    } else {
                        out += `    ${vSafe} = ${bOut};\n`;
                    }
                }
            } else {
                // Function Block Execution
                const instName = data.instanceName || type;
                let iSafe = instName.trim().replace(/\s+/g, '_');

                let callTarget = iSafe;
                if (category === 'program') {
                    callTarget = `prog_${parentName}_inst_${iSafe}`;
                } else if (category === 'function_block') {
                    callTarget = `instance->${iSafe}`;
                }

                out += `    ${bOut} = ${inExpr};\n`;

                if (data.values) {
                    Object.entries(data.values).forEach(([pinName, val]) => {
                        if (!val) return;
                        let safeVal = val.trim();
                        // IEC Time Format Converter (e.g. T#5s -> 5000000, T#500ms -> 500000)
                        if (safeVal.toUpperCase().startsWith('T#') || safeVal.toUpperCase().startsWith('TIME#')) {
                            safeVal = mapIECtoTimeUs(safeVal).toString();
                        } else if (isNaN(safeVal) && typeof safeVal === 'string') {
                            // If it's a variable reference
                            safeVal = safeVal.replace(/\s+/g, '_');
                            if (category === 'program') {
                                safeVal = `prog_${parentName}_${safeVal}`;
                            } else if (category === 'function_block') {
                                safeVal = `instance->${safeVal}`;
                            }
                        }
                        out += `    ${callTarget}.${pinName} = ${safeVal};\n`;
                    });
                }

                // Better approach: we rely on the specific standard function names to set the right trigger pin.
                if (type === 'TON' || type === 'TOF' || type === 'TP') {
                    out += `    ${callTarget}.IN = ${inExpr};\n`;
                } else if (type === 'CTU') {
                    out += `    ${callTarget}.CU = ${inExpr};\n`;
                } else if (type === 'CTD') {
                    out += `    ${callTarget}.CD = ${inExpr};\n`;
                } else if (type === 'R_TRIG' || type === 'F_TRIG') {
                    out += `    ${callTarget}.CLK = ${inExpr};\n`;
                } else if (type === 'RS' || type === 'SR') {
                    out += `    ${callTarget}.S = ${inExpr};\n`; // Note: RS is S, SR is S1 usually but let's stick to what we know mapping is.
                }

                if (stdFunctions[type]) {
                    const timeArg = stdFunctions[type].hasTime ? ', us_tick' : '';
                    out += `    ${type}_Call(&${callTarget}${timeArg});\n`;
                } else {
                    out += `    ${type}_Execute(&${callTarget});\n`;
                }

                // For the next block in the chain, it should consume the output `Q` of this block
                if (type === 'TON' || type === 'TOF' || type === 'TP' || type === 'CTU' || type === 'CTD' || type === 'R_TRIG' || type === 'F_TRIG') {
                    out += `    ${bOut} = ${callTarget}.Q;\n`;
                } else if (type === 'RS' || type === 'SR') {
                    out += `    ${bOut} = ${callTarget}.Q1;\n`;
                } else {
                    out += `    ${bOut} = ${callTarget}.ENO;\n`; // Generic fallback
                }
            }
        });
    });

    return out;
};

const mapType = (iecType) => {
    const typeMap = {
        'BOOL': 'bool',
        'SINT': 'int8_t',
        'INT': 'int16_t',
        'DINT': 'int32_t',
        'LINT': 'int64_t',
        'USINT': 'uint8_t',
        'UINT': 'uint16_t',
        'UDINT': 'uint32_t',
        'ULINT': 'uint64_t',
        'REAL': 'float',
        'LREAL': 'double',
        'BYTE': 'uint8_t',
        'WORD': 'uint16_t',
        'DWORD': 'uint32_t',
        'LWORD': 'uint64_t',
        'TIME': 'uint32_t',
        'STRING': 'char*',
        'VOID': 'void'
    };
    return typeMap[iecType] || iecType; // Fallback to custom name
};

const transpileDataType = (dt) => {
    let code = '';
    if (dt.type === 'Enumerated') {
        code += `typedef enum {\n`;
        dt.content.values.forEach((val, i) => {
            code += `    ${val.identifier}${val.value ? ` = ${val.value}` : ''}${i < dt.content.values.length - 1 ? ',' : ''}\n`;
        });
        code += `} ${dt.name};\n\n`;
    } else if (dt.type === 'Structure') {
        code += `typedef struct {\n`;
        dt.content.members.forEach(member => {
            code += `    ${mapType(member.type)} ${member.name};\n`;
        });
        code += `} ${dt.name};\n\n`;
    } else if (dt.type === 'Array') {
        const totalSize = dt.content.dimensions.reduce((acc, dim) => acc * ((parseInt(dim.max) - parseInt(dim.min)) + 1), 1);
        code += `typedef struct {\n`;
        code += `    ${mapType(dt.content.baseType)} data[${totalSize}];\n`;
        code += `} ${dt.name};\n\n`;
    }
    return code;
};
