// Board definitions for KronEditor
// Each board family contains variants with hardware specs and pinout data

// Standard 40-pin Raspberry Pi GPIO Header (shared by Pi 3B, 3B+, 4B, Zero 2W)
const RPI_40PIN_HEADER = [
  { pin: 1,  name: '3V3',      type: 'power',  color: '#ff6b35' },
  { pin: 2,  name: '5V',       type: 'power',  color: '#ff0000' },
  { pin: 3,  name: 'GPIO2',    type: 'gpio',   alt: 'SDA1 (I2C)', color: '#4a90d9' },
  { pin: 4,  name: '5V',       type: 'power',  color: '#ff0000' },
  { pin: 5,  name: 'GPIO3',    type: 'gpio',   alt: 'SCL1 (I2C)', color: '#4a90d9' },
  { pin: 6,  name: 'GND',      type: 'ground', color: '#333333' },
  { pin: 7,  name: 'GPIO4',    type: 'gpio',   alt: 'GPCLK0', color: '#4caf50' },
  { pin: 8,  name: 'GPIO14',   type: 'gpio',   alt: 'TXD (UART)', color: '#9c27b0' },
  { pin: 9,  name: 'GND',      type: 'ground', color: '#333333' },
  { pin: 10, name: 'GPIO15',   type: 'gpio',   alt: 'RXD (UART)', color: '#9c27b0' },
  { pin: 11, name: 'GPIO17',   type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 12, name: 'GPIO18',   type: 'gpio',   alt: 'PCM_CLK / PWM0', color: '#4caf50' },
  { pin: 13, name: 'GPIO27',   type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 14, name: 'GND',      type: 'ground', color: '#333333' },
  { pin: 15, name: 'GPIO22',   type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 16, name: 'GPIO23',   type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 17, name: '3V3',      type: 'power',  color: '#ff6b35' },
  { pin: 18, name: 'GPIO24',   type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 19, name: 'GPIO10',   type: 'gpio',   alt: 'MOSI (SPI0)', color: '#ff9800' },
  { pin: 20, name: 'GND',      type: 'ground', color: '#333333' },
  { pin: 21, name: 'GPIO9',    type: 'gpio',   alt: 'MISO (SPI0)', color: '#ff9800' },
  { pin: 22, name: 'GPIO25',   type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 23, name: 'GPIO11',   type: 'gpio',   alt: 'SCLK (SPI0)', color: '#ff9800' },
  { pin: 24, name: 'GPIO8',    type: 'gpio',   alt: 'CE0 (SPI0)', color: '#ff9800' },
  { pin: 25, name: 'GND',      type: 'ground', color: '#333333' },
  { pin: 26, name: 'GPIO7',    type: 'gpio',   alt: 'CE1 (SPI0)', color: '#ff9800' },
  { pin: 27, name: 'ID_SD',    type: 'special', alt: 'EEPROM SDA', color: '#607d8b' },
  { pin: 28, name: 'ID_SC',    type: 'special', alt: 'EEPROM SCL', color: '#607d8b' },
  { pin: 29, name: 'GPIO5',    type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 30, name: 'GND',      type: 'ground', color: '#333333' },
  { pin: 31, name: 'GPIO6',    type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 32, name: 'GPIO12',   type: 'gpio',   alt: 'PWM0', color: '#4caf50' },
  { pin: 33, name: 'GPIO13',   type: 'gpio',   alt: 'PWM1', color: '#4caf50' },
  { pin: 34, name: 'GND',      type: 'ground', color: '#333333' },
  { pin: 35, name: 'GPIO19',   type: 'gpio',   alt: 'PCM_FS / SPI1 MISO', color: '#4caf50' },
  { pin: 36, name: 'GPIO16',   type: 'gpio',   alt: 'SPI1 CE2', color: '#4caf50' },
  { pin: 37, name: 'GPIO26',   type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 38, name: 'GPIO20',   type: 'gpio',   alt: 'SPI1 MOSI', color: '#4caf50' },
  { pin: 39, name: 'GND',      type: 'ground', color: '#333333' },
  { pin: 40, name: 'GPIO21',   type: 'gpio',   alt: 'SPI1 SCLK', color: '#4caf50' },
];

// Generic 40-pin RPi-compatible header, shared by third-party aarch64 SBCs
// (Orange Pi, Radxa, Odroid, Banana Pi, Libre Computer, Pine64). These boards
// advertise Raspberry Pi-compatible 40-pin headers, so the RPi layout is used
// as a close-enough visual reference. Signal names are indicative only —
// actual gpiochip line offsets and bus numbers are SoC-specific; run
// `gpioinfo` / check /dev/i2c-* and /dev/ttyS* on the target to confirm.
const GENERIC_40PIN_HEADER = RPI_40PIN_HEADER;

// Raspberry Pi 5 40-pin GPIO Header — RP1 I/O controller.
// PWM: 2 logical channels (PWM0, PWM1). Each channel can be routed to
// exactly one of two candidate GPIOs, so PWM0 is EITHER on GPIO12 OR on
// GPIO18, and PWM1 is EITHER on GPIO13 OR on GPIO19 — never both at
// once. The HAL picks the routing selected via /boot/firmware/config.txt
// (dtoverlay=pwm-2chan). Pin labels list both candidates so the user can
// see the options without implying simultaneous availability.
const RPI5_40PIN_HEADER = [
  { pin: 1,  name: '3V3',      type: 'power',  color: '#ff6b35' },
  { pin: 2,  name: '5V',       type: 'power',  color: '#ff0000' },
  { pin: 3,  name: 'GPIO2',    type: 'gpio',   alt: 'SDA1 (I2C)', color: '#4a90d9' },
  { pin: 4,  name: '5V',       type: 'power',  color: '#ff0000' },
  { pin: 5,  name: 'GPIO3',    type: 'gpio',   alt: 'SCL1 (I2C)', color: '#4a90d9' },
  { pin: 6,  name: 'GND',      type: 'ground', color: '#333333' },
  { pin: 7,  name: 'GPIO4',    type: 'gpio',   alt: 'GPCLK0', color: '#4caf50' },
  { pin: 8,  name: 'GPIO14',   type: 'gpio',   alt: 'TXD (UART)', color: '#9c27b0' },
  { pin: 9,  name: 'GND',      type: 'ground', color: '#333333' },
  { pin: 10, name: 'GPIO15',   type: 'gpio',   alt: 'RXD (UART)', color: '#9c27b0' },
  { pin: 11, name: 'GPIO17',   type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 12, name: 'GPIO18',   type: 'gpio',   alt: 'PCM_CLK / PWM0 (alt)', color: '#4caf50' },
  { pin: 13, name: 'GPIO27',   type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 14, name: 'GND',      type: 'ground', color: '#333333' },
  { pin: 15, name: 'GPIO22',   type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 16, name: 'GPIO23',   type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 17, name: '3V3',      type: 'power',  color: '#ff6b35' },
  { pin: 18, name: 'GPIO24',   type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 19, name: 'GPIO10',   type: 'gpio',   alt: 'MOSI (SPI0)', color: '#ff9800' },
  { pin: 20, name: 'GND',      type: 'ground', color: '#333333' },
  { pin: 21, name: 'GPIO9',    type: 'gpio',   alt: 'MISO (SPI0)', color: '#ff9800' },
  { pin: 22, name: 'GPIO25',   type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 23, name: 'GPIO11',   type: 'gpio',   alt: 'SCLK (SPI0)', color: '#ff9800' },
  { pin: 24, name: 'GPIO8',    type: 'gpio',   alt: 'CE0 (SPI0)', color: '#ff9800' },
  { pin: 25, name: 'GND',      type: 'ground', color: '#333333' },
  { pin: 26, name: 'GPIO7',    type: 'gpio',   alt: 'CE1 (SPI0)', color: '#ff9800' },
  { pin: 27, name: 'ID_SD',    type: 'special', alt: 'EEPROM SDA', color: '#607d8b' },
  { pin: 28, name: 'ID_SC',    type: 'special', alt: 'EEPROM SCL', color: '#607d8b' },
  { pin: 29, name: 'GPIO5',    type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 30, name: 'GND',      type: 'ground', color: '#333333' },
  { pin: 31, name: 'GPIO6',    type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 32, name: 'GPIO12',   type: 'gpio',   alt: 'PWM0 (default)', color: '#4caf50' },
  { pin: 33, name: 'GPIO13',   type: 'gpio',   alt: 'PWM1 (default)', color: '#4caf50' },
  { pin: 34, name: 'GND',      type: 'ground', color: '#333333' },
  { pin: 35, name: 'GPIO19',   type: 'gpio',   alt: 'PCM_FS / PWM1 (alt)', color: '#4caf50' },
  { pin: 36, name: 'GPIO16',   type: 'gpio',   alt: 'SPI1 CE2', color: '#4caf50' },
  { pin: 37, name: 'GPIO26',   type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 38, name: 'GPIO20',   type: 'gpio',   alt: 'SPI1 MOSI', color: '#4caf50' },
  { pin: 39, name: 'GND',      type: 'ground', color: '#333333' },
  { pin: 40, name: 'GPIO21',   type: 'gpio',   alt: 'SPI1 SCLK', color: '#4caf50' },
];


// BeagleBone P9 header
const BB_P9_HEADER = [
  { pin: 1,  name: 'GND',       type: 'ground', color: '#333333' },
  { pin: 2,  name: 'GND',       type: 'ground', color: '#333333' },
  { pin: 3,  name: 'VDD_3V3',   type: 'power',  color: '#ff6b35' },
  { pin: 4,  name: 'VDD_3V3',   type: 'power',  color: '#ff6b35' },
  { pin: 5,  name: 'VDD_5V',    type: 'power',  color: '#ff0000' },
  { pin: 6,  name: 'VDD_5V',    type: 'power',  color: '#ff0000' },
  { pin: 7,  name: 'SYS_5V',    type: 'power',  color: '#ff0000' },
  { pin: 8,  name: 'SYS_5V',    type: 'power',  color: '#ff0000' },
  { pin: 9,  name: 'PWR_BUT',   type: 'special', color: '#607d8b' },
  { pin: 10, name: 'SYS_RESET', type: 'special', color: '#607d8b' },
  { pin: 11, name: 'GPIO0_30',  type: 'gpio',   alt: 'UART4_RXD', color: '#4caf50' },
  { pin: 12, name: 'GPIO1_28',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 13, name: 'GPIO0_31',  type: 'gpio',   alt: 'UART4_TXD', color: '#4caf50' },
  { pin: 14, name: 'GPIO1_18',  type: 'gpio',   alt: 'EHRPWM1A', color: '#4caf50' },
  { pin: 15, name: 'GPIO1_16',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 16, name: 'GPIO1_19',  type: 'gpio',   alt: 'EHRPWM1B', color: '#4caf50' },
  { pin: 17, name: 'GPIO0_5',   type: 'gpio',   alt: 'I2C1_SCL', color: '#4a90d9' },
  { pin: 18, name: 'GPIO0_4',   type: 'gpio',   alt: 'I2C1_SDA', color: '#4a90d9' },
  { pin: 19, name: 'GPIO0_13',  type: 'gpio',   alt: 'I2C2_SCL', color: '#4a90d9' },
  { pin: 20, name: 'GPIO0_12',  type: 'gpio',   alt: 'I2C2_SDA', color: '#4a90d9' },
  { pin: 21, name: 'GPIO0_3',   type: 'gpio',   alt: 'UART2_TXD', color: '#9c27b0' },
  { pin: 22, name: 'GPIO0_2',   type: 'gpio',   alt: 'UART2_RXD', color: '#9c27b0' },
  { pin: 23, name: 'GPIO1_17',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 24, name: 'GPIO0_15',  type: 'gpio',   alt: 'UART1_TXD', color: '#9c27b0' },
  { pin: 25, name: 'GPIO3_21',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 26, name: 'GPIO0_14',  type: 'gpio',   alt: 'UART1_RXD', color: '#9c27b0' },
  { pin: 27, name: 'GPIO3_19',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 28, name: 'GPIO3_17',  type: 'gpio',   alt: 'SPI1_CS0', color: '#ff9800' },
  { pin: 29, name: 'GPIO3_15',  type: 'gpio',   alt: 'SPI1_D0', color: '#ff9800' },
  { pin: 30, name: 'GPIO3_16',  type: 'gpio',   alt: 'SPI1_D1', color: '#ff9800' },
  { pin: 31, name: 'GPIO3_14',  type: 'gpio',   alt: 'SPI1_SCLK', color: '#ff9800' },
  { pin: 32, name: 'VDD_ADC',   type: 'power',  alt: '1.8V ADC', color: '#ff6b35' },
  { pin: 33, name: 'AIN4',      type: 'analog', alt: 'ADC Ch4', color: '#e91e63' },
  { pin: 34, name: 'GND_ADC',   type: 'ground', color: '#333333' },
  { pin: 35, name: 'AIN6',      type: 'analog', alt: 'ADC Ch6', color: '#e91e63' },
  { pin: 36, name: 'AIN5',      type: 'analog', alt: 'ADC Ch5', color: '#e91e63' },
  { pin: 37, name: 'AIN2',      type: 'analog', alt: 'ADC Ch2', color: '#e91e63' },
  { pin: 38, name: 'AIN3',      type: 'analog', alt: 'ADC Ch3', color: '#e91e63' },
  { pin: 39, name: 'AIN0',      type: 'analog', alt: 'ADC Ch0', color: '#e91e63' },
  { pin: 40, name: 'AIN1',      type: 'analog', alt: 'ADC Ch1', color: '#e91e63' },
  { pin: 41, name: 'GPIO0_20',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 42, name: 'GPIO0_7',   type: 'gpio',   alt: 'eCAP0', color: '#4caf50' },
  { pin: 43, name: 'GND',       type: 'ground', color: '#333333' },
  { pin: 44, name: 'GND',       type: 'ground', color: '#333333' },
  { pin: 45, name: 'GND',       type: 'ground', color: '#333333' },
  { pin: 46, name: 'GND',       type: 'ground', color: '#333333' },
];

// Jetson 40-pin header — compatible physical layout with RPi 40-pin header.
// PIN values in HAL blocks must be gpiochip0 line offsets for your board.
// Run `gpioinfo /dev/gpiochip0` on the target to discover line numbers.
const JETSON_40PIN_HEADER = [
  { pin: 1,  name: '3V3',       type: 'power',  color: '#ff6b35' },
  { pin: 2,  name: '5V',        type: 'power',  color: '#ff0000' },
  { pin: 3,  name: 'I2C_SDA',   type: 'gpio',   alt: 'I2C Bus 1 SDA', color: '#4a90d9' },
  { pin: 4,  name: '5V',        type: 'power',  color: '#ff0000' },
  { pin: 5,  name: 'I2C_SCL',   type: 'gpio',   alt: 'I2C Bus 1 SCL', color: '#4a90d9' },
  { pin: 6,  name: 'GND',       type: 'ground', color: '#333333' },
  { pin: 7,  name: 'GPIO_09',   type: 'gpio',   alt: 'AUD_MCLK', color: '#4caf50' },
  { pin: 8,  name: 'UART_TX',   type: 'gpio',   alt: 'THS UART TX', color: '#9c27b0' },
  { pin: 9,  name: 'GND',       type: 'ground', color: '#333333' },
  { pin: 10, name: 'UART_RX',   type: 'gpio',   alt: 'THS UART RX', color: '#9c27b0' },
  { pin: 11, name: 'UART_RTS',  type: 'gpio',   alt: 'UART RTS / GPIO', color: '#4caf50' },
  { pin: 12, name: 'I2S_CLK',   type: 'gpio',   alt: 'I2S / GPIO', color: '#4caf50' },
  { pin: 13, name: 'GPIO_11',   type: 'gpio',   alt: 'SPI SCK / GPIO', color: '#4caf50' },
  { pin: 14, name: 'GND',       type: 'ground', color: '#333333' },
  { pin: 15, name: 'GPIO_19',   type: 'gpio',   alt: 'LCD_TE / GPIO', color: '#4caf50' },
  { pin: 16, name: 'GPIO_08',   type: 'gpio',   alt: 'SPI CS1 / GPIO', color: '#4caf50' },
  { pin: 17, name: '3V3',       type: 'power',  color: '#ff6b35' },
  { pin: 18, name: 'GPIO_20',   type: 'gpio',   alt: 'LCD_RST / GPIO', color: '#4caf50' },
  { pin: 19, name: 'SPI_MOSI',  type: 'gpio',   alt: 'SPI0 MOSI', color: '#ff9800' },
  { pin: 20, name: 'GND',       type: 'ground', color: '#333333' },
  { pin: 21, name: 'SPI_MISO',  type: 'gpio',   alt: 'SPI0 MISO', color: '#ff9800' },
  { pin: 22, name: 'GPIO_25',   type: 'gpio',   alt: 'SPI CS0 / GPIO', color: '#4caf50' },
  { pin: 23, name: 'SPI_SCK',   type: 'gpio',   alt: 'SPI0 SCLK', color: '#ff9800' },
  { pin: 24, name: 'SPI_CS0',   type: 'gpio',   alt: 'SPI0 CS0', color: '#ff9800' },
  { pin: 25, name: 'GND',       type: 'ground', color: '#333333' },
  { pin: 26, name: 'SPI_CS1',   type: 'gpio',   alt: 'SPI0 CS1', color: '#ff9800' },
  { pin: 27, name: 'I2C0_SDA',  type: 'gpio',   alt: 'I2C Bus 0 SDA', color: '#607d8b' },
  { pin: 28, name: 'I2C0_SCL',  type: 'gpio',   alt: 'I2C Bus 0 SCL', color: '#607d8b' },
  { pin: 29, name: 'GPIO_01',   type: 'gpio',   alt: 'CAM_AF_EN / GPIO', color: '#4caf50' },
  { pin: 30, name: 'GND',       type: 'ground', color: '#333333' },
  { pin: 31, name: 'GPIO_00',   type: 'gpio',   alt: 'UART CTS / GPIO', color: '#4caf50' },
  { pin: 32, name: 'GPIO_12',   type: 'gpio',   alt: 'LCD_BL_PWM / PWM', color: '#4caf50' },
  { pin: 33, name: 'GPIO_13',   type: 'gpio',   alt: 'SPI2 MOSI / GPIO', color: '#4caf50' },
  { pin: 34, name: 'GND',       type: 'ground', color: '#333333' },
  { pin: 35, name: 'I2S_FS',    type: 'gpio',   alt: 'I2S / GPIO', color: '#4caf50' },
  { pin: 36, name: 'UART_CTS',  type: 'gpio',   alt: 'UART CTS / GPIO', color: '#4caf50' },
  { pin: 37, name: 'GPIO_26',   type: 'gpio',   alt: 'SPI2 MISO / GPIO', color: '#4caf50' },
  { pin: 38, name: 'I2S_DIN',   type: 'gpio',   alt: 'I2S / GPIO', color: '#4caf50' },
  { pin: 39, name: 'GND',       type: 'ground', color: '#333333' },
  { pin: 40, name: 'I2S_DOUT',  type: 'gpio',   alt: 'I2S / GPIO', color: '#4caf50' },
];

// Jetson Orin Nano/NX/AGX Orin 40-pin header (Tegra234, AliCam overlay)
// GPIO: SPI3→GPIO pins 13/16/18/22/37 (port Y, gpiochip0 lines 192-196).
// PWM (verified on device): pin 15→pwm1/pwmchip0 (3280000.pwm), pin 32→pwm7/pwmchip3 (32e0000.pwm),
//                            pin 33→pwm5/pwmchip2 (32c0000.pwm). Note: pwmchipN shifts per boot;
//                            HAL resolves by controller address symlink, not chip number.
// I2C: pins 3/5 (I2C8, bus 8) and 27/28 (I2C2, bus 2) on AON gpiochip1.
// UART1: pins 8/10/11/36. SPI1: pins 19/21/23/24/26.
const ORIN_40PIN_HEADER = [
  { pin: 1,  name: '3V3',       type: 'power',  color: '#ff6b35' },
  { pin: 2,  name: '5V',        type: 'power',  color: '#ff0000' },
  { pin: 3,  name: 'I2C_SDA',   type: 'gpio',   alt: 'I2C8 SDA (bus 8)', color: '#4a90d9' },
  { pin: 4,  name: '5V',        type: 'power',  color: '#ff0000' },
  { pin: 5,  name: 'I2C_SCL',   type: 'gpio',   alt: 'I2C8 SCL (bus 8)', color: '#4a90d9' },
  { pin: 6,  name: 'GND',       type: 'ground', color: '#333333' },
  { pin: 7,  name: 'AUD_MCLK',  type: 'gpio',   alt: 'Audio MCLK (pac6)', color: '#4caf50' },
  { pin: 8,  name: 'UART_TX',   type: 'gpio',   alt: 'UART1 TX (pr2)', color: '#9c27b0' },
  { pin: 9,  name: 'GND',       type: 'ground', color: '#333333' },
  { pin: 10, name: 'UART_RX',   type: 'gpio',   alt: 'UART1 RX (pr3)', color: '#9c27b0' },
  { pin: 11, name: 'UART_RTS',  type: 'gpio',   alt: 'UART1 RTS (pr4)', color: '#9c27b0' },
  { pin: 12, name: 'I2S_CLK',   type: 'gpio',   alt: 'I2S2 SCLK (ph7)', color: '#4caf50' },
  { pin: 13, name: 'GPIO_PY0',  type: 'gpio',   alt: 'GPIO (py0 line 192)', color: '#4caf50' },
  { pin: 14, name: 'GND',       type: 'ground', color: '#333333' },
  { pin: 15, name: 'PWM0',      type: 'gpio',   alt: 'PWM0 – pwm1 controller (3280000.pwm) → pin 15', color: '#ff9800' },
  { pin: 16, name: 'GPIO_PY4',  type: 'gpio',   alt: 'GPIO (py4 line 196)', color: '#4caf50' },
  { pin: 17, name: '3V3',       type: 'power',  color: '#ff6b35' },
  { pin: 18, name: 'GPIO_PY3',  type: 'gpio',   alt: 'GPIO (py3 line 195)', color: '#4caf50' },
  { pin: 19, name: 'SPI_MOSI',  type: 'gpio',   alt: 'SPI1 MOSI (pz5)', color: '#ff9800' },
  { pin: 20, name: 'GND',       type: 'ground', color: '#333333' },
  { pin: 21, name: 'SPI_MISO',  type: 'gpio',   alt: 'SPI1 MISO (pz4)', color: '#ff9800' },
  { pin: 22, name: 'GPIO_PY1',  type: 'gpio',   alt: 'GPIO (py1 line 193)', color: '#4caf50' },
  { pin: 23, name: 'SPI_SCK',   type: 'gpio',   alt: 'SPI1 SCLK (pz3)', color: '#ff9800' },
  { pin: 24, name: 'SPI_CS0',   type: 'gpio',   alt: 'SPI1 CS0 (pz6)', color: '#ff9800' },
  { pin: 25, name: 'GND',       type: 'ground', color: '#333333' },
  { pin: 26, name: 'SPI_CS1',   type: 'gpio',   alt: 'SPI1 CS1 (pz7)', color: '#ff9800' },
  { pin: 27, name: 'I2C0_SDA',  type: 'gpio',   alt: 'I2C2 SDA (bus 2)', color: '#607d8b' },
  { pin: 28, name: 'I2C0_SCL',  type: 'gpio',   alt: 'I2C2 SCL (bus 2)', color: '#607d8b' },
  { pin: 29, name: 'MCLK3',     type: 'gpio',   alt: 'extperiph3 CLK (pq5)', color: '#4caf50' },
  { pin: 30, name: 'GND',       type: 'ground', color: '#333333' },
  { pin: 31, name: 'MCLK4',     type: 'gpio',   alt: 'extperiph4 CLK (pq6)', color: '#4caf50' },
  { pin: 32, name: 'PWM1',      type: 'gpio',   alt: 'PWM1 – pwm7 controller (32e0000.pwm) → pin 32', color: '#ff9800' },
  { pin: 33, name: 'PWM2',      type: 'gpio',   alt: 'PWM2 – pwm5 controller (32c0000.pwm) → pin 33', color: '#ff9800' },
  { pin: 34, name: 'GND',       type: 'ground', color: '#333333' },
  { pin: 35, name: 'I2S_FS',    type: 'gpio',   alt: 'I2S2 FS (pi2)', color: '#4caf50' },
  { pin: 36, name: 'UART_CTS',  type: 'gpio',   alt: 'UART1 CTS (pr5)', color: '#9c27b0' },
  { pin: 37, name: 'GPIO_PY2',  type: 'gpio',   alt: 'GPIO (py2 line 194)', color: '#4caf50' },
  { pin: 38, name: 'I2S_DIN',   type: 'gpio',   alt: 'I2S2 DIN (pi1)', color: '#4caf50' },
  { pin: 39, name: 'GND',       type: 'ground', color: '#333333' },
  { pin: 40, name: 'I2S_DOUT',  type: 'gpio',   alt: 'I2S2 DOUT (pi0)', color: '#4caf50' },
];

// BeagleBone P8 header
const BB_P8_HEADER = [
  { pin: 1,  name: 'GND',       type: 'ground', color: '#333333' },
  { pin: 2,  name: 'GND',       type: 'ground', color: '#333333' },
  { pin: 3,  name: 'GPIO1_6',   type: 'gpio',   alt: 'MMC1_DAT6', color: '#4caf50' },
  { pin: 4,  name: 'GPIO1_7',   type: 'gpio',   alt: 'MMC1_DAT7', color: '#4caf50' },
  { pin: 5,  name: 'GPIO1_2',   type: 'gpio',   alt: 'MMC1_DAT2', color: '#4caf50' },
  { pin: 6,  name: 'GPIO1_3',   type: 'gpio',   alt: 'MMC1_DAT3', color: '#4caf50' },
  { pin: 7,  name: 'GPIO2_2',   type: 'gpio',   alt: 'TIMER4', color: '#4caf50' },
  { pin: 8,  name: 'GPIO2_3',   type: 'gpio',   alt: 'TIMER7', color: '#4caf50' },
  { pin: 9,  name: 'GPIO2_5',   type: 'gpio',   alt: 'TIMER5', color: '#4caf50' },
  { pin: 10, name: 'GPIO2_4',   type: 'gpio',   alt: 'TIMER6', color: '#4caf50' },
  { pin: 11, name: 'GPIO1_13',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 12, name: 'GPIO1_12',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 13, name: 'GPIO0_23',  type: 'gpio',   alt: 'EHRPWM2B', color: '#4caf50' },
  { pin: 14, name: 'GPIO0_26',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 15, name: 'GPIO1_15',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 16, name: 'GPIO1_14',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 17, name: 'GPIO0_27',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 18, name: 'GPIO2_1',   type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 19, name: 'GPIO0_22',  type: 'gpio',   alt: 'EHRPWM2A', color: '#4caf50' },
  { pin: 20, name: 'GPIO1_31',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 21, name: 'GPIO1_30',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 22, name: 'GPIO1_5',   type: 'gpio',   alt: 'MMC1_DAT5', color: '#4caf50' },
  { pin: 23, name: 'GPIO1_4',   type: 'gpio',   alt: 'MMC1_DAT4', color: '#4caf50' },
  { pin: 24, name: 'GPIO1_1',   type: 'gpio',   alt: 'MMC1_DAT1', color: '#4caf50' },
  { pin: 25, name: 'GPIO1_0',   type: 'gpio',   alt: 'MMC1_DAT0', color: '#4caf50' },
  { pin: 26, name: 'GPIO1_29',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 27, name: 'GPIO2_22',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 28, name: 'GPIO2_24',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 29, name: 'GPIO2_23',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 30, name: 'GPIO2_25',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 31, name: 'GPIO0_10',  type: 'gpio',   alt: 'UART5_CTS', color: '#4caf50' },
  { pin: 32, name: 'GPIO0_11',  type: 'gpio',   alt: 'UART5_RTS', color: '#4caf50' },
  { pin: 33, name: 'GPIO0_9',   type: 'gpio',   alt: 'UART4_RTS', color: '#4caf50' },
  { pin: 34, name: 'GPIO2_17',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 35, name: 'GPIO0_8',   type: 'gpio',   alt: 'UART4_CTS', color: '#4caf50' },
  { pin: 36, name: 'GPIO2_16',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 37, name: 'GPIO2_14',  type: 'gpio',   alt: 'UART5_TXD', color: '#4caf50' },
  { pin: 38, name: 'GPIO2_15',  type: 'gpio',   alt: 'UART5_RXD', color: '#4caf50' },
  { pin: 39, name: 'GPIO2_12',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 40, name: 'GPIO2_13',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 41, name: 'GPIO2_10',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 42, name: 'GPIO2_11',  type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 43, name: 'GPIO2_8',   type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 44, name: 'GPIO2_9',   type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 45, name: 'GPIO2_6',   type: 'gpio',   alt: '', color: '#4caf50' },
  { pin: 46, name: 'GPIO2_7',   type: 'gpio',   alt: '', color: '#4caf50' },
];

export const BOARD_FAMILIES = [
  {
    name: 'Raspberry Pi',
    icon: '🍓',
    boards: [
      {
        id: 'rpi_5',
        name: 'Raspberry Pi 5',
        cpu: 'Broadcom BCM2712 (Quad Cortex-A76 @ 2.4GHz)',
        arch: 'aarch64',
        ram: '4GB / 8GB LPDDR4X',
        storage: 'microSD / NVMe (M.2 HAT)',
        connectivity: 'WiFi 5, BT 5.0, Gigabit Ethernet',
        gpio: 40,
        usb: '2x USB 3.0, 2x USB 2.0',
        display: '2x micro HDMI (4Kp60)',
        pinout: RPI5_40PIN_HEADER,
        pinLayout: 'rpi40',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'PCM', 'USB'],
        usbPorts: [
          { id: 'USB_0', type: 'USB 3.0', connector: 'Type-A' },
          { id: 'USB_1', type: 'USB 3.0', connector: 'Type-A' },
          { id: 'USB_2', type: 'USB 2.0', connector: 'Type-A' },
          { id: 'USB_3', type: 'USB 2.0', connector: 'Type-A' },
        ],
      },
      {
        id: 'rpi_4b',
        name: 'Raspberry Pi 4 Model B',
        cpu: 'Broadcom BCM2711 (Quad Cortex-A72 @ 1.8GHz)',
        arch: 'aarch64',
        ram: '2GB / 4GB / 8GB LPDDR4',
        storage: 'microSD',
        connectivity: 'WiFi 5, BT 5.0, Gigabit Ethernet',
        gpio: 40,
        usb: '2x USB 3.0, 2x USB 2.0',
        display: '2x micro HDMI (4Kp60)',
        pinout: RPI_40PIN_HEADER,
        pinLayout: 'rpi40',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'PCM', 'USB'],
        usbPorts: [
          { id: 'USB_0', type: 'USB 3.0', connector: 'Type-A' },
          { id: 'USB_1', type: 'USB 3.0', connector: 'Type-A' },
          { id: 'USB_2', type: 'USB 2.0', connector: 'Type-A' },
          { id: 'USB_3', type: 'USB 2.0', connector: 'Type-A' },
        ],
      },
      {
        id: 'rpi_3b_plus',
        name: 'Raspberry Pi 3 Model B+',
        cpu: 'Broadcom BCM2837B0 (Quad Cortex-A53 @ 1.4GHz)',
        arch: 'aarch64',
        ram: '1GB LPDDR2',
        storage: 'microSD',
        connectivity: 'WiFi 4, BT 4.2, Gigabit Ethernet (300Mbps)',
        gpio: 40,
        usb: '4x USB 2.0',
        display: 'HDMI (1080p)',
        pinout: RPI_40PIN_HEADER,
        pinLayout: 'rpi40',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'PCM', 'USB'],
        usbPorts: [
          { id: 'USB_0', type: 'USB 2.0', connector: 'Type-A' },
          { id: 'USB_1', type: 'USB 2.0', connector: 'Type-A' },
          { id: 'USB_2', type: 'USB 2.0', connector: 'Type-A' },
          { id: 'USB_3', type: 'USB 2.0', connector: 'Type-A' },
        ],
      },
      {
        id: 'rpi_3b',
        name: 'Raspberry Pi 3 Model B',
        cpu: 'Broadcom BCM2837 (Quad Cortex-A53 @ 1.2GHz)',
        arch: 'aarch64',
        ram: '1GB LPDDR2',
        storage: 'microSD',
        connectivity: 'WiFi 4, BT 4.1, 100Mbps Ethernet',
        gpio: 40,
        usb: '4x USB 2.0',
        display: 'HDMI (1080p)',
        pinout: RPI_40PIN_HEADER,
        pinLayout: 'rpi40',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'PCM', 'USB'],
        usbPorts: [
          { id: 'USB_0', type: 'USB 2.0', connector: 'Type-A' },
          { id: 'USB_1', type: 'USB 2.0', connector: 'Type-A' },
          { id: 'USB_2', type: 'USB 2.0', connector: 'Type-A' },
          { id: 'USB_3', type: 'USB 2.0', connector: 'Type-A' },
        ],
      },
      {
        id: 'rpi_zero_2w',
        name: 'Raspberry Pi Zero 2 W',
        cpu: 'Broadcom BCM2710A1 (Quad Cortex-A53 @ 1GHz)',
        arch: 'aarch64',
        ram: '512MB LPDDR2',
        storage: 'microSD',
        connectivity: 'WiFi 4, BT 4.2',
        gpio: 40,
        usb: '1x micro USB (OTG)',
        display: 'mini HDMI',
        pinout: RPI_40PIN_HEADER,
        pinLayout: 'rpi40',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'PCM', 'USB'],
        usbPorts: [
          { id: 'USB_0', type: 'USB 2.0', connector: 'Micro-B (OTG)' },
        ],
      },
    ]
  },
  {
    name: 'BeagleBone',
    icon: '🦴',
    boards: [
      {
        id: 'bb_black',
        name: 'BeagleBone Black',
        cpu: 'TI AM3358 (Cortex-A8 @ 1GHz)',
        arch: 'armv7',
        ram: '512MB DDR3',
        storage: '4GB eMMC + microSD',
        connectivity: '10/100 Ethernet',
        gpio: 65,
        usb: '1x USB 2.0 Host, 1x mini USB Client',
        display: 'micro HDMI',
        pinout: { P8: BB_P8_HEADER, P9: BB_P9_HEADER },
        pinLayout: 'beaglebone',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'ADC', 'CAN', 'PRU', 'USB'],
        usbPorts: [
          { id: 'USB_0', type: 'USB 2.0', connector: 'Type-A (Host)' },
          { id: 'USB_1', type: 'USB 2.0', connector: 'Mini-B (Client)' },
        ],
      },
      {
        id: 'bb_black_wireless',
        name: 'BeagleBone Black Wireless',
        cpu: 'TI AM3358 (Cortex-A8 @ 1GHz)',
        arch: 'armv7',
        ram: '512MB DDR3',
        storage: '4GB eMMC + microSD',
        connectivity: 'WiFi, BT 4.1',
        gpio: 65,
        usb: '1x USB 2.0 Host, 1x mini USB Client',
        display: 'micro HDMI',
        pinout: { P8: BB_P8_HEADER, P9: BB_P9_HEADER },
        pinLayout: 'beaglebone',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'ADC', 'CAN', 'PRU', 'USB'],
        usbPorts: [
          { id: 'USB_0', type: 'USB 2.0', connector: 'Type-A (Host)' },
          { id: 'USB_1', type: 'USB 2.0', connector: 'Mini-B (Client)' },
        ],
      },
      {
        id: 'bb_green',
        name: 'BeagleBone Green',
        cpu: 'TI AM3358 (Cortex-A8 @ 1GHz)',
        arch: 'armv7',
        ram: '512MB DDR3',
        storage: '4GB eMMC + microSD',
        connectivity: '10/100 Ethernet',
        gpio: 65,
        usb: '1x USB 2.0 Host, 1x mini USB Client',
        display: 'N/A (No HDMI)',
        pinout: { P8: BB_P8_HEADER, P9: BB_P9_HEADER },
        pinLayout: 'beaglebone',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'ADC', 'CAN', 'PRU', 'Grove', 'USB'],
        usbPorts: [
          { id: 'USB_0', type: 'USB 2.0', connector: 'Type-A (Host)' },
          { id: 'USB_1', type: 'USB 2.0', connector: 'Mini-B (Client)' },
        ],
      },
      {
        id: 'bb_green_wireless',
        name: 'BeagleBone Green Wireless',
        cpu: 'TI AM3358 (Cortex-A8 @ 1GHz)',
        arch: 'armv7',
        ram: '512MB DDR3',
        storage: '4GB eMMC + microSD',
        connectivity: 'WiFi, BT 4.1',
        gpio: 65,
        usb: '1x USB 2.0 Host, 1x micro USB Client',
        display: 'N/A (No HDMI)',
        pinout: { P8: BB_P8_HEADER, P9: BB_P9_HEADER },
        pinLayout: 'beaglebone',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'ADC', 'CAN', 'PRU', 'Grove', 'USB'],
        usbPorts: [
          { id: 'USB_0', type: 'USB 2.0', connector: 'Micro-B (Client)' },
        ],
      },
      {
        id: 'bb_ai',
        name: 'BeagleBone AI',
        cpu: 'TI AM5729 (Dual Cortex-A15 @ 1.5GHz)',
        arch: 'armv7',
        ram: '1GB DDR3L',
        storage: '16GB eMMC + microSD',
        connectivity: 'WiFi 5, BT 4.2, Gigabit Ethernet',
        gpio: 65,
        usb: '1x USB 3.0 Type-A, 1x USB Type-C',
        display: 'micro HDMI',
        pinout: { P8: BB_P8_HEADER, P9: BB_P9_HEADER },
        pinLayout: 'beaglebone',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'ADC', 'CAN', 'PRU', 'USB'],
        usbPorts: [
          { id: 'USB_0', type: 'USB 3.0', connector: 'Type-A' },
          { id: 'USB_1', type: 'USB 2.0', connector: 'Type-C' },
        ],
      },
      {
        id: 'bb_ai64',
        name: 'BeagleBone AI-64',
        cpu: 'TI TDA4VM (Dual Cortex-A72 @ 2GHz)',
        arch: 'aarch64',
        ram: '4GB LPDDR4',
        storage: '16GB eMMC + microSD',
        connectivity: 'WiFi 6, BT 5.1, Gigabit Ethernet',
        gpio: 65,
        usb: '2x USB 3.0 Type-A, 1x USB Type-C',
        display: 'mini DP, micro HDMI',
        pinout: { P8: BB_P8_HEADER, P9: BB_P9_HEADER },
        pinLayout: 'beaglebone',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'ADC', 'CAN', 'PRU', 'CSI', 'USB'],
        usbPorts: [
          { id: 'USB_0', type: 'USB 3.0', connector: 'Type-A' },
          { id: 'USB_1', type: 'USB 3.0', connector: 'Type-A' },
          { id: 'USB_2', type: 'USB 2.0', connector: 'Type-C' },
        ],
      },
    ]
  },
  {
    name: 'NVIDIA Jetson',
    icon: '🤖',
    boards: [
      {
        id: 'jetson_nano',
        name: 'Jetson Nano Developer Kit',
        cpu: 'NVIDIA Tegra X1 (Quad Cortex-A57 @ 1.48GHz)',
        arch: 'aarch64',
        ram: '4GB LPDDR4',
        storage: 'microSD / eMMC (production module)',
        connectivity: 'Gigabit Ethernet',
        gpio: 40,
        usb: '4x USB 3.0, 1x micro USB (power/device)',
        display: 'HDMI 2.0, DP 1.2',
        pinout: JETSON_40PIN_HEADER,
        pinLayout: 'rpi40',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'USB'],
        usbPorts: [
          { id: 'USB_0', type: 'USB 3.0', connector: 'Type-A' },
          { id: 'USB_1', type: 'USB 3.0', connector: 'Type-A' },
          { id: 'USB_2', type: 'USB 3.0', connector: 'Type-A' },
          { id: 'USB_3', type: 'USB 3.0', connector: 'Type-A' },
          { id: 'USB_4', type: 'USB 2.0', connector: 'Micro-B (Device)' },
        ],
      },
      {
        id: 'jetson_tx2',
        name: 'Jetson TX2 Developer Kit',
        cpu: 'NVIDIA Parker (Dual Denver 2 + Quad Cortex-A57 @ 2GHz)',
        arch: 'aarch64',
        ram: '8GB LPDDR4',
        storage: '32GB eMMC',
        connectivity: 'Gigabit Ethernet, WiFi 802.11ac, BT 4.1',
        gpio: 40,
        usb: '3x USB 3.0, 1x USB 2.0',
        display: 'HDMI 2.0, DP 1.2, eDP 1.4',
        pinout: JETSON_40PIN_HEADER,
        pinLayout: 'rpi40',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'CAN', 'USB'],
        usbPorts: [
          { id: 'USB_0', type: 'USB 3.0', connector: 'Type-A' },
          { id: 'USB_1', type: 'USB 3.0', connector: 'Type-A' },
          { id: 'USB_2', type: 'USB 3.0', connector: 'Type-A' },
          { id: 'USB_3', type: 'USB 2.0', connector: 'Type-A' },
        ],
      },
      {
        id: 'jetson_xavier_nx',
        name: 'Jetson Xavier NX Developer Kit',
        cpu: 'NVIDIA Volta (6-core Carmel ARMv8.2 @ 1.9GHz)',
        arch: 'aarch64',
        ram: '8GB / 16GB LPDDR4x',
        storage: 'microSD / 16GB eMMC',
        connectivity: 'Gigabit Ethernet, WiFi 802.11ac, BT 5.0',
        gpio: 40,
        usb: '4x USB 3.1 Gen 2, 1x USB 2.0 Micro-B',
        display: 'HDMI 2.0, DP 1.4',
        pinout: JETSON_40PIN_HEADER,
        pinLayout: 'rpi40',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'CAN', 'USB'],
        usbPorts: [
          { id: 'USB_0', type: 'USB 3.1', connector: 'Type-A' },
          { id: 'USB_1', type: 'USB 3.1', connector: 'Type-A' },
          { id: 'USB_2', type: 'USB 3.1', connector: 'Type-A' },
          { id: 'USB_3', type: 'USB 3.1', connector: 'Type-A' },
          { id: 'USB_4', type: 'USB 2.0', connector: 'Micro-B (Device)' },
        ],
      },
      {
        id: 'jetson_agx_xavier',
        name: 'Jetson AGX Xavier Developer Kit',
        cpu: 'NVIDIA Xavier (8-core Carmel ARMv8.2 @ 2.265GHz)',
        arch: 'aarch64',
        ram: '16GB / 32GB LPDDR4x',
        storage: '32GB eMMC',
        connectivity: 'Gigabit Ethernet',
        gpio: 40,
        usb: '2x USB 3.1 Gen 2 Type-A, 1x USB 3.1 Gen 2 Type-C',
        display: 'HDMI 2.0, DP 1.4, eDP 1.4',
        pinout: JETSON_40PIN_HEADER,
        pinLayout: 'rpi40',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'CAN', 'USB'],
        usbPorts: [
          { id: 'USB_0', type: 'USB 3.1 Gen 2', connector: 'Type-A' },
          { id: 'USB_1', type: 'USB 3.1 Gen 2', connector: 'Type-A' },
          { id: 'USB_2', type: 'USB 3.1 Gen 2', connector: 'Type-C' },
        ],
      },
      {
        id: 'jetson_orin_nano',
        name: 'Jetson Orin Nano Developer Kit',
        cpu: 'NVIDIA Orin (6-core Cortex-A78AE @ 1.5GHz)',
        arch: 'aarch64',
        ram: '4GB / 8GB LPDDR5',
        storage: 'microSD',
        connectivity: 'Gigabit Ethernet',
        gpio: 40,
        usb: '4x USB 3.2 Gen 2, 1x USB 2.0 Micro-B',
        display: 'HDMI 2.1, DP 1.4',
        pinout: ORIN_40PIN_HEADER,
        pinLayout: 'rpi40',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'CAN', 'USB'],
        usbPorts: [
          { id: 'USB_0', type: 'USB 3.2 Gen 2', connector: 'Type-A' },
          { id: 'USB_1', type: 'USB 3.2 Gen 2', connector: 'Type-A' },
          { id: 'USB_2', type: 'USB 3.2 Gen 2', connector: 'Type-A' },
          { id: 'USB_3', type: 'USB 3.2 Gen 2', connector: 'Type-A' },
          { id: 'USB_4', type: 'USB 2.0', connector: 'Micro-B' },
        ],
      },
      {
        id: 'jetson_orin_nx',
        name: 'Jetson Orin NX Developer Kit',
        cpu: 'NVIDIA Orin (8/10-core Cortex-A78AE @ 2GHz)',
        arch: 'aarch64',
        ram: '8GB / 16GB LPDDR5',
        storage: 'microSD / NVMe',
        connectivity: 'Gigabit Ethernet',
        gpio: 40,
        usb: '4x USB 3.2 Gen 2, 1x USB 2.0 Micro-B',
        display: 'HDMI 2.1, DP 1.4',
        pinout: ORIN_40PIN_HEADER,
        pinLayout: 'rpi40',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'CAN', 'USB'],
        usbPorts: [
          { id: 'USB_0', type: 'USB 3.2 Gen 2', connector: 'Type-A' },
          { id: 'USB_1', type: 'USB 3.2 Gen 2', connector: 'Type-A' },
          { id: 'USB_2', type: 'USB 3.2 Gen 2', connector: 'Type-A' },
          { id: 'USB_3', type: 'USB 3.2 Gen 2', connector: 'Type-A' },
          { id: 'USB_4', type: 'USB 2.0', connector: 'Micro-B' },
        ],
      },
      {
        id: 'jetson_agx_orin',
        name: 'Jetson AGX Orin Developer Kit',
        cpu: 'NVIDIA Orin (12-core Cortex-A78AE @ 2.2GHz)',
        arch: 'aarch64',
        ram: '32GB / 64GB LPDDR5',
        storage: '64GB eMMC / NVMe',
        connectivity: 'Gigabit Ethernet (2x)',
        gpio: 40,
        usb: '4x USB 3.2 Gen 2 Type-A, 1x USB 3.2 Gen 2 Type-C',
        display: 'HDMI 2.1, DP 1.4, eDP 1.4',
        pinout: ORIN_40PIN_HEADER,
        pinLayout: 'rpi40',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'CAN', 'USB'],
        usbPorts: [
          { id: 'USB_0', type: 'USB 3.2 Gen 2', connector: 'Type-A' },
          { id: 'USB_1', type: 'USB 3.2 Gen 2', connector: 'Type-A' },
          { id: 'USB_2', type: 'USB 3.2 Gen 2', connector: 'Type-A' },
          { id: 'USB_3', type: 'USB 3.2 Gen 2', connector: 'Type-A' },
          { id: 'USB_4', type: 'USB 3.2 Gen 2', connector: 'Type-C' },
        ],
      },
    ]
  },
  // ── Third-party aarch64 Linux SBC families ─────────────────────────────────
  // These vendors are grouped as separate display families, but their board-id
  // prefixes (opi_, radxa_, odroid_, bpi_, libre_, pine_) all map to
  // HAL_BOARD_FAMILY_RPI in getBoardFamilyDefine: they reuse the generic Linux
  // userspace HAL (kronhal_rpi.h — gpiod, /dev/i2c-*, /dev/spidev*, /dev/tty*)
  // until board-specific HAL headers are written. All boards are aarch64, so
  // the host-agent's default compile triple (aarch64-linux-gnu) and the
  // prebuilt aarch64 server binary apply without changes.
  {
    name: 'Orange Pi',
    icon: '🍊',
    boards: [
      {
        id: 'opi_5',
        name: 'Orange Pi 5',
        cpu: 'Rockchip RK3588S (4x Cortex-A76 @ 2.4GHz + 4x Cortex-A55)',
        arch: 'aarch64',
        ram: '4GB / 8GB / 16GB LPDDR4X',
        storage: 'microSD / M.2 NVMe',
        connectivity: 'Gigabit Ethernet',
        gpio: 40,
        usb: '1x USB 3.0, 2x USB 2.0, 1x USB-C 3.0',
        display: 'HDMI 2.1 (8K)',
        pinout: GENERIC_40PIN_HEADER,
        pinLayout: 'rpi40',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'CAN', 'USB'],
        usbPorts: [
          { id: 'USB_0', type: 'USB 3.0', connector: 'Type-A' },
          { id: 'USB_1', type: 'USB 2.0', connector: 'Type-A' },
          { id: 'USB_2', type: 'USB 2.0', connector: 'Type-A' },
          { id: 'USB_3', type: 'USB 3.0', connector: 'Type-C' },
        ],
      },
      {
        id: 'opi_5_plus',
        name: 'Orange Pi 5 Plus',
        cpu: 'Rockchip RK3588 (4x Cortex-A76 @ 2.4GHz + 4x Cortex-A55)',
        arch: 'aarch64',
        ram: '4GB – 32GB LPDDR4X',
        storage: 'eMMC socket / microSD / M.2 NVMe',
        connectivity: '2x 2.5G Ethernet',
        gpio: 40,
        usb: '2x USB 3.0, 2x USB 2.0, 1x USB-C 3.0',
        display: '2x HDMI 2.1 (8K)',
        pinout: GENERIC_40PIN_HEADER,
        pinLayout: 'rpi40',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'CAN', 'USB'],
        usbPorts: [
          { id: 'USB_0', type: 'USB 3.0', connector: 'Type-A' },
          { id: 'USB_1', type: 'USB 3.0', connector: 'Type-A' },
          { id: 'USB_2', type: 'USB 2.0', connector: 'Type-A' },
          { id: 'USB_3', type: 'USB 2.0', connector: 'Type-A' },
          { id: 'USB_4', type: 'USB 3.0', connector: 'Type-C' },
        ],
      },
      {
        id: 'opi_zero_2w',
        name: 'Orange Pi Zero 2W',
        cpu: 'Allwinner H618 (4x Cortex-A53 @ 1.5GHz)',
        arch: 'aarch64',
        ram: '1GB / 1.5GB / 2GB / 4GB LPDDR4',
        storage: 'microSD',
        connectivity: 'WiFi 5, BT 5.0',
        gpio: 40,
        usb: '1x USB-C 2.0 (OTG)',
        display: 'mini HDMI 2.0',
        pinout: GENERIC_40PIN_HEADER,
        pinLayout: 'rpi40',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'USB'],
        usbPorts: [
          { id: 'USB_0', type: 'USB 2.0', connector: 'Type-C (OTG)' },
        ],
      },
    ]
  },
  {
    name: 'Radxa',
    icon: '🪨',
    boards: [
      {
        id: 'radxa_rock_5b',
        name: 'Radxa ROCK 5B',
        cpu: 'Rockchip RK3588 (4x Cortex-A76 @ 2.4GHz + 4x Cortex-A55)',
        arch: 'aarch64',
        ram: '4GB / 8GB / 16GB LPDDR4X',
        storage: 'eMMC socket / microSD / M.2 NVMe',
        connectivity: '2.5G Ethernet',
        gpio: 40,
        usb: '2x USB 3.0, 2x USB 2.0, 1x USB-C 3.0',
        display: '2x HDMI 2.1 (8K)',
        pinout: GENERIC_40PIN_HEADER,
        pinLayout: 'rpi40',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'CAN', 'USB'],
        usbPorts: [
          { id: 'USB_0', type: 'USB 3.0', connector: 'Type-A' },
          { id: 'USB_1', type: 'USB 3.0', connector: 'Type-A' },
          { id: 'USB_2', type: 'USB 2.0', connector: 'Type-A' },
          { id: 'USB_3', type: 'USB 2.0', connector: 'Type-A' },
          { id: 'USB_4', type: 'USB 3.0', connector: 'Type-C' },
        ],
      },
      {
        id: 'radxa_rock_3a',
        name: 'Radxa ROCK 3A',
        cpu: 'Rockchip RK3568 (4x Cortex-A55 @ 2.0GHz)',
        arch: 'aarch64',
        ram: '2GB / 4GB / 8GB LPDDR4',
        storage: 'eMMC socket / microSD / M.2 NVMe',
        connectivity: 'Gigabit Ethernet',
        gpio: 40,
        usb: '2x USB 3.0, 2x USB 2.0',
        display: 'HDMI 2.0 (4K)',
        pinout: GENERIC_40PIN_HEADER,
        pinLayout: 'rpi40',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'USB'],
        usbPorts: [
          { id: 'USB_0', type: 'USB 3.0', connector: 'Type-A' },
          { id: 'USB_1', type: 'USB 3.0', connector: 'Type-A (OTG)' },
          { id: 'USB_2', type: 'USB 2.0', connector: 'Type-A' },
          { id: 'USB_3', type: 'USB 2.0', connector: 'Type-A' },
        ],
      },
      {
        id: 'radxa_zero_3w',
        name: 'Radxa Zero 3W',
        cpu: 'Rockchip RK3566 (4x Cortex-A55 @ 1.6GHz)',
        arch: 'aarch64',
        ram: '1GB – 8GB LPDDR4',
        storage: 'eMMC / microSD',
        connectivity: 'WiFi 4/5, BT 5.0',
        gpio: 40,
        usb: '1x USB-C 3.0, 1x USB-C 2.0 (OTG)',
        display: 'micro HDMI (4K)',
        pinout: GENERIC_40PIN_HEADER,
        pinLayout: 'rpi40',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'USB'],
        usbPorts: [
          { id: 'USB_0', type: 'USB 3.0', connector: 'Type-C' },
          { id: 'USB_1', type: 'USB 2.0', connector: 'Type-C (OTG)' },
        ],
      },
    ]
  },
  {
    name: 'Odroid',
    icon: '🔷',
    boards: [
      {
        id: 'odroid_c4',
        name: 'Odroid C4',
        cpu: 'Amlogic S905X3 (4x Cortex-A55 @ 2.0GHz)',
        arch: 'aarch64',
        ram: '4GB DDR4',
        storage: 'eMMC socket / microSD',
        connectivity: 'Gigabit Ethernet',
        gpio: 40,
        usb: '4x USB 3.0, 1x micro USB 2.0 (OTG)',
        display: 'HDMI 2.0 (4K)',
        pinout: GENERIC_40PIN_HEADER,
        pinLayout: 'rpi40',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'ADC', 'USB'],
        usbPorts: [
          { id: 'USB_0', type: 'USB 3.0', connector: 'Type-A' },
          { id: 'USB_1', type: 'USB 3.0', connector: 'Type-A' },
          { id: 'USB_2', type: 'USB 3.0', connector: 'Type-A' },
          { id: 'USB_3', type: 'USB 3.0', connector: 'Type-A' },
        ],
      },
      {
        id: 'odroid_n2_plus',
        name: 'Odroid N2+',
        cpu: 'Amlogic S922X (4x Cortex-A73 @ 2.4GHz + 2x Cortex-A53)',
        arch: 'aarch64',
        ram: '2GB / 4GB DDR4',
        storage: 'eMMC socket / microSD',
        connectivity: 'Gigabit Ethernet',
        gpio: 40,
        usb: '4x USB 3.0, 1x micro USB 2.0 (OTG)',
        display: 'HDMI 2.0 (4K)',
        pinout: GENERIC_40PIN_HEADER,
        pinLayout: 'rpi40',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'USB'],
        usbPorts: [
          { id: 'USB_0', type: 'USB 3.0', connector: 'Type-A' },
          { id: 'USB_1', type: 'USB 3.0', connector: 'Type-A' },
          { id: 'USB_2', type: 'USB 3.0', connector: 'Type-A' },
          { id: 'USB_3', type: 'USB 3.0', connector: 'Type-A' },
        ],
      },
    ]
  },
  {
    name: 'Banana Pi',
    icon: '🍌',
    boards: [
      {
        id: 'bpi_m5',
        name: 'Banana Pi BPI-M5',
        cpu: 'Amlogic S905X3 (4x Cortex-A55 @ 2.0GHz)',
        arch: 'aarch64',
        ram: '4GB LPDDR4',
        storage: '16GB eMMC + microSD',
        connectivity: 'Gigabit Ethernet',
        gpio: 40,
        usb: '4x USB 3.0',
        display: 'HDMI 2.1 (4K)',
        pinout: GENERIC_40PIN_HEADER,
        pinLayout: 'rpi40',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'USB'],
        usbPorts: [
          { id: 'USB_0', type: 'USB 3.0', connector: 'Type-A' },
          { id: 'USB_1', type: 'USB 3.0', connector: 'Type-A' },
          { id: 'USB_2', type: 'USB 3.0', connector: 'Type-A' },
          { id: 'USB_3', type: 'USB 3.0', connector: 'Type-A' },
        ],
      },
    ]
  },
  {
    name: 'Libre Computer',
    icon: '🥔',
    boards: [
      {
        id: 'libre_le_potato',
        name: 'Le Potato (AML-S905X-CC)',
        cpu: 'Amlogic S905X (4x Cortex-A53 @ 1.512GHz)',
        arch: 'aarch64',
        ram: '1GB / 2GB DDR3',
        storage: 'eMMC socket / microSD',
        connectivity: '100Mbps Ethernet',
        gpio: 40,
        usb: '4x USB 2.0',
        display: 'HDMI 2.0 (4K)',
        pinout: GENERIC_40PIN_HEADER,
        pinLayout: 'rpi40',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'USB'],
        usbPorts: [
          { id: 'USB_0', type: 'USB 2.0', connector: 'Type-A' },
          { id: 'USB_1', type: 'USB 2.0', connector: 'Type-A' },
          { id: 'USB_2', type: 'USB 2.0', connector: 'Type-A' },
          { id: 'USB_3', type: 'USB 2.0', connector: 'Type-A' },
        ],
      },
    ]
  },
  {
    name: 'Pine64',
    icon: '🌲',
    boards: [
      {
        id: 'pine_rock64',
        name: 'Rock64',
        cpu: 'Rockchip RK3328 (4x Cortex-A53 @ 1.5GHz)',
        arch: 'aarch64',
        ram: '1GB / 2GB / 4GB LPDDR3',
        storage: 'eMMC socket / microSD',
        connectivity: 'Gigabit Ethernet',
        gpio: 40,
        usb: '1x USB 3.0, 2x USB 2.0',
        display: 'HDMI 2.0 (4K)',
        pinout: GENERIC_40PIN_HEADER,
        pinLayout: 'rpi40',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'USB'],
        usbPorts: [
          { id: 'USB_0', type: 'USB 3.0', connector: 'Type-A' },
          { id: 'USB_1', type: 'USB 2.0', connector: 'Type-A' },
          { id: 'USB_2', type: 'USB 2.0', connector: 'Type-A' },
        ],
      },
      {
        id: 'pine_rockpro64',
        name: 'ROCKPro64',
        cpu: 'Rockchip RK3399 (2x Cortex-A72 @ 1.8GHz + 4x Cortex-A53)',
        arch: 'aarch64',
        ram: '2GB / 4GB LPDDR4',
        storage: 'eMMC socket / microSD / PCIe NVMe',
        connectivity: 'Gigabit Ethernet',
        gpio: 40,
        usb: '1x USB 3.0, 2x USB 2.0, 1x USB-C 3.0',
        display: 'HDMI 2.0 (4K)',
        pinout: GENERIC_40PIN_HEADER,
        pinLayout: 'rpi40',
        interfaces: ['GPIO', 'I2C', 'SPI', 'UART', 'PWM', 'USB'],
        usbPorts: [
          { id: 'USB_0', type: 'USB 3.0', connector: 'Type-A' },
          { id: 'USB_1', type: 'USB 2.0', connector: 'Type-A' },
          { id: 'USB_2', type: 'USB 2.0', connector: 'Type-A' },
          { id: 'USB_3', type: 'USB 3.0', connector: 'Type-C' },
        ],
      },
    ]
  }
];

// Flat lookup helper
export function getBoardById(boardId) {
  for (const family of BOARD_FAMILIES) {
    const board = family.boards.find(b => b.id === boardId);
    if (board) return { ...board, family: family.name };
  }
  return null;
}

// Get family of a board
export function getBoardFamily(boardId) {
  for (const family of BOARD_FAMILIES) {
    if (family.boards.some(b => b.id === boardId)) return family.name;
  }
  return null;
}
